executable              = execution.sh
arguments               = $(ClusterId)$(ProcId)
output                  = test.$(ClusterId).$(ProcId).out
error                   = test.$(ClusterId).$(ProcId).err
log                     = test.$(ClusterId).log
should_transfer_files   = YES
transfer_input_files    = ./comparison.py, ./stratified_mc.py  
transfer_output_files   = data.tar.gz
when_to_transfer_output = ON_EXIT
+JobFlavour = "tomorrow"
request_GPUs = 1
request_CPUs = 1
queue
